name: Docker Image CI

on:
    push:
        branches: ['main', 'master']
    pull_request:
        branches: ['main', 'master']

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Determine Version
              run: echo "NXRM_VERSION=$(grep release Dockerfile  | cut -d "=" -f2 | tr -d '" \')" >> $GITHUB_ENV

            - run: echo "Building NXRM ${{ env.NXRM_VERSION }} for ARM"

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.REGISTRY_USERNAME }}
                  password: ${{ secrets.REGISTRY_TOKEN }}

            - name: Build and push Java 8
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile
                  platforms: linux/arm64,linux/amd64
                  push: true
                  tags: ${{ secrets.REGISTRY_USERNAME }}/nexus3:latest , ${{ secrets.REGISTRY_USERNAME }}/nexus3:${{ env.NXRM_VERSION }}

            - name: Build and push Java 11
              uses: docker/build-push-action@v5
              with:
                  context: .
                  file: ./Dockerfile.java11
                  platforms: linux/arm64,linux/amd64
                  push: true
                  tags: ${{ secrets.REGISTRY_USERNAME }}/nexus3:${{ env.NXRM_VERSION }}-java11
